project:
  type: website
  output-dir: _site
  render:
    - about/index.qmd
    - about/overview.qmd
    - about/syllabus.qmd
    - chapters/*/chapter*.qmd
    - chapters/*/slides/*.qmd
    - chapters/*/slides/*.Rmd
    - resources/*
    - assets/styles.css
website:
  title: "Structural Equation Modeling"
  sidebar:
    logo: assets/images/course_logo.png
    style: "docked"
    search: true
    tools:
      - icon: github
        href: https://github.com/xcit-courses/sem-1
        text: "GitHub"
      - icon: cloud-fill
        href: https://posit.cloud/
        text: "RStudio Cloud"
      - icon: person-fill
        href: https://uni.lu
        text: "UniLu"
    contents:
      - text: Home
        href: about/index.qmd
      - section: Course Information
        contents:
          - text: Overview
            href: about/overview.qmd
          - text: Syllabus
            href: about/syllabus.qmd

      - section: Chapters
        contents:
          - text: "1 - Introduction to SEM"
            href: chapters/chapter1/chapter1.qmd
          - text: "2 - Descriptive Statistics"
            href: chapters/chapter2/chapter2.qmd
          - text: "3 - Probability Distributions"
            href: chapters/chapter3/chapter3.qmd
          # - text: "4 - Simple Linear Regression"
          #   href: chapters/chapter4/chapter4.qmd
          # - text: "5 - Multiple Linear Regression"
          #   href: chapters/chapter5/chapter5.qmd
          # - text: "6 - Moderation and Mediation"
          #   href: chapters/chapter6/chapter6.qmd
          # - text: "7 - Factor Analysis"
          #   href: chapters/chapter7/chapter7.qmd
          # - text: "8 - Path Analysis"
          #   href: chapters/chapter8/chapter8.qmd
          # - text: "9 - Structural Equation Modeling"
          #   href: chapters/chapter9/chapter9.qmd
          # - text: "10 - Advanced Topics"
          #   href: chapters/chapter10/chapter10.qmd
      - text: Resources
        href: resources/resources.md

  page-footer:
    left: ""
    right: "Built with [Quarto](https://quarto.org/)"
  page-navigation: true

book:
  chapters:
    - about/index.qmd
    - part: "Course Information"
      chapters:
        - about/overview.qmd
        - about/syllabus.qmd
    - part: "Chapters"
      chapters:
        - chapters/chapter1/chapter1.qmd
        - chapters/chapter2/chapter2.qmd
        # - chapters/chapter3/chapter3.qmd
        # - chapters/chapter4/chapter4.qmd
        # - chapters/chapter5/chapter5.qmd
        # - chapters/chapter6/chapter6.qmd
        # - chapters/chapter7/chapter7.qmd
        # - chapters/chapter8/chapter8.qmd
        # - chapters/chapter9/chapter9.qmd
        # - chapters/chapter10/chapter10.qmd
    - resources/resources.md

format:
  html:
    theme:
      - lux
      - assets/styles.css
    toc: true
    code-copy: true
    code-overflow: wrap
    link-external-newwindow: true
    color-scheme: auto
